### ISSUE TITLE
Reg file does not apply tweaks when using CMD script

### ISSUE THREAD

**Issue by thepcwiz101** [thepcwiz101/Internet-Speed-Tweak#4]
Due to a limitation or security feature in windows the registry tweaks won't work without running the network.reg file manually.

**Comment by GenesisFR** [comment]
Might be worth checking if using "reg.exe" instead of "regedit.exe" can circumvent it as it doesn't need admin rights, it's available since XP if I remember well.

**Comment by thepcwiz101** [comment]
@GenesisFR reg.exe still has to use admin rights but it solved the issue. Thanks for the help.

**Comment by GenesisFR** [comment]
Congratz, glad it worked!
